import 'package:flutter/cupertino.dart';

class AboutWidget extends StatelessWidget {
  const AboutWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container(
      child: Padding(
        padding: EdgeInsets.all(14.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            Text('Icon Resources:'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
            Text('https://www.freepik.com/vectors/badge'),
          ],
        ),
      ),
    );
  }
}
